name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true


env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself
  NODE_NO_WARNINGS: 1

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm lint:fix

  Build_Dev:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm turbo --filter ember-canary-vite build:dev
      - run: pnpm turbo build:dev
      - uses: actions/upload-artifact@v4
        with:
          name: deploy-prep-dev
          if-no-files-found: error
          path: |
            ./benchmark/dist/**

  Build_Prod:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm turbo --filter ember-canary-vite build:prod
      - run: pnpm turbo build:prod
      - uses: actions/upload-artifact@v4
        with:
          name: deploy-prep-prod
          if-no-files-found: error
          path: |
            ./benchmark/dist/**

##############################################################
##############################################################
#
# These jobs won't run on pull requests.
# They would fail anyway because secrets are not exposed.
#
##############################################################
##############################################################

  Deploy_Dev:
    name: "Deploy: Dev"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 15
    needs: [Build_Dev]
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        name: deploy-prep-dev
      - name: Preview Dev
        working-directory: ./deploy-prep-dev/
        run: |
          ls -la
          npx wrangler pages deploy ./ \
            --project-name=ember-performance-testing-dev \
            --branch=${{ github.event.workflow_run.head_branch }} \
            --commit-hash=${{ github.event.workflow_run.head_sha }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  Deploy_Prod:
    name: "Deploy: Prod"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 15
    needs: [Build_Prod]
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        name: deploy-prep-prod
      - name: Preview Prod
        working-directory: ./deploy-prep-prod/
        run: |
          ls -la
          npx wrangler pages deploy ./ \
            --project-name=ember-performance-testing-prod \
            --branch=${{ github.event.workflow_run.head_branch }} \
            --commit-hash=${{ github.event.workflow_run.head_sha }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

